backend:
  name: github
  repo: ugcclausanne/ugcc-site

  # local_backend: true
  branch: main
  auth_type: implicit
  base_url: https://github.com/login/oauth/authorize/
  # auth_endpoint: /authorize
  client_id: Ov23liHLc5n9hbQnfvVB
  # app_id:  2154474
  

# token_endpoint: /token
publish_mode: editorial_workflow
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date",  label: "Date",      widget: "datetime" }
      - { name: "body",  label: "Text",     widget: "markdown" }
