backend:
  name: github
  repo: ugcclausanne/ugcc-site
  branch: main
  # ВИДАЛІТЬ base_url та auth_url
  client_id: Ov23li8cbPFh52mLWFFS
  auth_endpoint: https://github.com/login/oauth/authorize
  auth_scope: repo


# token_endpoint: /token
publish_mode: editorial_workflow
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date",  label: "Date",      widget: "datetime" }
      - { name: "body",  label: "Text",     widget: "markdown" }
