backend:
  name: github
  repo: "ugcclausanne/ugcc-site"
  branch: "main"
  auth_type: implicit        # <-- додано: використовувати GitHub implicit OAuth
  auth_scope: "repo"         # <-- опціонально, явно просимо доступ до репозиторію
  client_id: "Iv23liIIRDw3tnhCPznq"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site content"
    files:
      - label: "Main site JSON"
        name: "site_json"
        file: "content/data/site.json"
        format: json
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Footer", name: "footer", widget: "text"}

  - name: "pages"
    label: "Pages"
    folder: "content/data/pages"
    create: true
    slug: "{{slug}}"
    format: json
    extension: ".json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Meta"
        name: "meta"
        widget: "object"
        fields:
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "string"}
