backend:
  name: github
  repo: ugcclausanne/ugcc-site
  branch: main
  auth_type: implicit
  app_id: 2144987

publish_mode: editorial_workflow

media_folder: assets/uploads
public_folder: /ugcc-site/assets/uploads

collections:
 - name: test
   label: Test
   folder: data/test
   create: true
   format: json
   extension: json
   fields:

   - { name: title, label: Title }