backend:
  name: github
  repo: ugcclausanne/ugcc-site
  branch: main
  # auth_type: implicit
  base_url: http://decap-oauth-proxy.netlify.app
  auth_endpoint: /auth
  client_id: Ov23liHLc5n9hbQnfvVB


publish_mode: editorial_workflow
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date",  label: "Date",      widget: "datetime" }
      - { name: "body",  label: "Text",     widget: "markdown" }
