backend:
  name: github
  repo: ugcclausanne/ugcc-site
  branch: main
  auth_type: implicit
  app_id: 75654

publish_mode: editorial_workflow

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "Новини"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Заголовок", widget: "string" }
      - { name: "date",  label: "Дата",      widget: "datetime" }
      - { name: "body",  label: "Текст",     widget: "markdown" }