name: Sync, Build, and (Optional) Autopost

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Sync from Sanity and build
        env:
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_API_VERSION: ${{ secrets.SANITY_API_VERSION }}
          SANITY_READ_TOKEN: ${{ secrets.SANITY_READ_TOKEN }}
          BASE_PATH: ${{ secrets.BASE_PATH }}
          # Optional translation
          TRANSLATE_PROVIDER: ${{ secrets.TRANSLATE_PROVIDER }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          LIBRE_TRANSLATE_URL: ${{ secrets.LIBRE_TRANSLATE_URL }}
        run: |
          npm run sync:sanity
          npm run build

      - name: Commit and push changes (skip CI)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "ci: sync from Sanity and build [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Autopost latest items (optional)
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          BASE_PATH: ${{ secrets.BASE_PATH }}
          POST_TO_FACEBOOK: ${{ secrets.POST_TO_FACEBOOK }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          POST_TO_INSTAGRAM: ${{ secrets.POST_TO_INSTAGRAM }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          POST_TO_WHATSAPP: ${{ secrets.POST_TO_WHATSAPP }}
          WA_PHONE_NUMBER_ID: ${{ secrets.WA_PHONE_NUMBER_ID }}
          WA_TOKEN: ${{ secrets.WA_TOKEN }}
          WA_RECIPIENTS: ${{ secrets.WA_RECIPIENTS }}
        run: |
          npm run post:publish || echo "Autopost skipped or failed; continuing."
