name: Merge data folders

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
      - 'scripts/merge-data.js'

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Merge data JSON
        run: node scripts/merge-data.js

      - name: Commit changes
        run: |
          if git diff --exit-code --quiet -- data/articles.json data/schedule.json; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/articles.json data/schedule.json
            git commit -m "chore(data): merge JSON folders into arrays [skip ci]"
            git push
          fi

